(setq files '("evil-lion.el"))
(setq byte-compile--use-old-handlers nil)
(setq byte-compile-error-on-warn t)
(mapc (lambda (file)
        (unless (byte-compile-file file)
          (kill-emacs 1)))
      files)
